
# html lang
language: en

# main menu navigation
menu:
  Home:
  About: about
  Contact: contact
  Archives: archives

# Miscelaneous
favicon: favicon.ico

# stylesheets loaded in the <head>
stylesheets:
- css/locize-theme.css

# scripts loaded in the end of the body
scripts:
- js/locize-theme.js
