# Menus
menu:
    Home: /
    # Delete this row if you don't want categories in your header nav bar
    # Categories:

subtitle: The continuous localization management platform that powers up your development and translation.

# Customize
customize:
    logo:
        width: 165
        height: 60
        url: images/locize_white.svg
        # root: /
        root: /blog/
    theme_color: '#15419A'
    highlight: androidstudio
    sidebar: left # sidebar position, options: left, right
    thumbnail: true # enable posts thumbnail, options: true, false
    favicon: favicon.ico # path to favicon
    social_links: # for more icons, please see http://fontawesome.io/icons/#brand
        x-twitter: https://x.com/locize
        youtube: https://www.youtube.com/channel/UCPYQjBbbXojUcB8qjeIB3uA
        facebook: https://www.facebook.com/locize
        # google-plus: /
        # github: https://github.com/ppoffice/hexo-theme-hueman
        # weibo: /
        # rss: /

# Widgets
widgets:
    - recent_posts
    # - category
    - archive
    # - tag
    - tagcloud
    - links

widgets_docs:
    - docs_integration
    - docs_more
    - recent_posts
    - links

# Search
search:
    insight: true # you need to install `hexo-generator-json-content` before using Insight Search
    swiftype: # enter swiftype install key here
    baidu: false # you need to disable other search engines to use Baidu search, options: true, false

# Comment
comment:
    disqus: # enter disqus shortname here
    duoshuo: # enter duoshuo shortname here
    youyan: # enter youyan uid here

# Share
share: default # options: jiathis, bdshare, addtoany, default

# Plugins
plugins:
    #fancybox: true # options: true, false
    lightgallery: true # options: true, false
    #scrollLoading: true # options: true, false
    google_analytics: G-X50E21BGKG # enter the tracking ID for your Google Analytics
    baidu_analytics: # enter Baidu Analytics hash key

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id: locize
        fb_admins:
        twitter_id: locize
        google_plus:
    links:
        # localistars: https://www.localistars.com
        i18next: https://www.i18next.com
        privacy policy: https://locize.com/privacy.html
        terms: https://locize.com/terms.html
